### ISSUE TITLE
GetDpiAwereness

### ISSUE THREAD

**Issue by Michael-DST** [firstfloorsoftware/mui#1]
Typo? :)

https://github.com/firstfloorsoftware/mui/blob/master/1.0/FirstFloor.ModernUI/Shared/ModernUIHelper.cs#L40

**Comment by kozw** [comment]
Yes, that's a typo. Correcting it introduces a breaking change, but it will happen nonetheless.

**Comment by Michael-DST** [comment]
Cool.  It is elsewhere in the code as well: https://github.com/firstfloorsoftware/mui/search?utf8=%E2%9C%93&q=awereness

Pretty awesome project otherwise.  I will be using it with my framework. :)

**Comment by kozw** [comment]
Fixed with commit 161ba3e9f9626538f83f52b57c448afe1622b376
