### ISSUE TITLE
Add Menu at Runtime

### ISSUE THREAD

**Issue by Loro77** [firstfloorsoftware/mui#116]
Hi and first at all I'm an newbie to c# MVVM, mui. I'm just a little embedded C programmer :-) 
I want to display an Menu in the main Window. Once the user has logged in. The visible meu options depend on the user's role. 
In my MainWindow.xaml File the ContentSource is set to "/View/Login_View.xaml"
to display the UserControl Login and the MenuCode is comment out. 

If the User clicked on the LoginButton, the Login_viewModel check if there is a valid User stored in a Database and get the role of this user. 

`LoginCommand = new RelayCommand(DoLogin);`
`private void DoLogin(object boj)`
`{` 
`//Do some database communication, to get the Userrole`
`//How to set the roel in MainWindow_ViewModel ?`
`}`

I found this Thread https://github.com/firstfloorsoftware/mui/issues/10 with a similar problem, but  I do not fully understand the ansewers/solutions.

In the MainWindow_ViewModel there ist an public Function

`public void DisplayMenu(string role)`
`{`
`if (role.Equals("User") )`
`{`
`var window = Application.Current.MainWindow as ModernWindow;`
`var library= new LinkGroup { DisplayName = "Books"};`
`library.Links.Add(new Link { DisplayName = "Serach" });`
`window.MenuLinkGroups.Add(library);`
`}`
`else if (role.Equals("Admin"))`
`{`
`var window = Application.Current.MainWindow as ModernWindow;`
`var library= new LinkGroup { DisplayName = "Books"};`
`library.Links.Add(new Link { DisplayName = "Serach" });`
`library.Links.Add(new Link { DisplayName = "Add" });`
`var Customer = new LinkGroup { DisplayName = "Customer"};`
`Customer.Customer.Add(new Link { DisplayName = "Serach" });`
`Customer.Customer.Add(new Link { DisplayName = "Add" });`
`window.MenuLinkGroups.Add(Customer);`
`}`
`}` 

I know that my first question has nothing to do with mui, but it depends to my main question. 
How can I use the DisplayMenu-Function out of the Login_ViewModel and how can I add the 
Source (Referencing to corresponding View.xaml) to the MenuLinks?

Thanks Chris

**Comment by Loro77** [comment]
Found a Solution to add a Source path
`library.Links.Add(new Link { DisplayName = "Search", Source = new System.Uri("/View/SearchBook.xaml", UriKind.Relative)});`

**Comment by KhairulAkmal2708** [comment]
Hai Loro77. Can I know the directives you used for 

                    var library = new LinkGroup { DisplayName = "Books" };
                    library.Links.Add(new Link { DisplayName = "Serach" });

**Comment by Loro77** [comment]
Hi KhairulAkmal2708 this is the directives I used:

using FirstFloor.ModernUI.Presentation;
using System;

**Comment by KhairulAkmal2708** [comment]
Thanks Loro77... peace be upon you..
