### ISSUE TITLE
Animate LogoData

### ISSUE THREAD

**Issue by SuricateCan** [firstfloorsoftware/mui#118]
Hi Dev team,

I want to use the LogoData as an activity indicator. When a certain activity is taking place, the logo should animate between some icons to create the illusion of movement.
Any way of accomplishing that without creating a background thread to do the job?

**Comment by sylveon** [comment]
Unfortunately, no.

The LogoData can only contain a static image. Nothing animated.

But, as you said, nothing prevents you from using a background thread for changing it 30 times per second.

**Comment by SuricateCan** [comment]
@charlesmilette Thanks for the answer.
