### ISSUE TITLE
Page does not refresh when clicked each time, only once it loads.

### ISSUE THREAD

**Issue by Hrchandra** [firstfloorsoftware/mui#127]
<mui:ModernTab >
        mui:ModernTab.Links

```
        <mui:Link DisplayName="Link1" Source="Page1.xaml"/>

        <mui:Link DisplayName="Link2" Source="Page2.xaml"/>

    </mui:ModernTab.Links>
</mui:ModernTab>
```

Hi, I have used the links in the same way, the problem is page doesn't refresh when it is clicked each time. Can anyone please help me how to reload the page each time when it is selected or clicked?

**Comment by prskr** [comment]
I think a possible approach would be to handle the navigation event of the ModernFrame in the MainWindow and refresh what ever you have to refresh in the view model or the code behind of your view. I don't think that it is possible to replace the mechanism which instantiates the views that easy, if you discover a solution, please tell me ;)

**Comment by Hrchandra** [comment]
Hi, I did this by adding the below event
private void UserControl_Loaded(object sender, RoutedEventArgs e)
        {
            this.DataContext = new ViewModel1();
        }
