### ISSUE TITLE
[Wiki] ContentRoot doesn't exist

### ISSUE THREAD

**Issue by einsteinsci** [firstfloorsoftware/mui#2]
I'm following the tutorials in VS2013, with MUI installed via NuGet, and apparently ContentRoot doesn't exist when used as told in the wiki.

**Comment by kozw** [comment]
The ```ContentRoot``` style is defined in ModernUI.xaml (source: /FirstFloor.ModernUI;component/Assets/ModernUI.xaml). Do you have this resource dictionary referenced in your App.xaml? The MUI project template Modern UI WPF Navigation Application' includes this resources dictionary automatically.

**Comment by einsteinsci** [comment]
Thanks. I redid the whole thing now and it's working.
