### ISSUE TITLE
Don't track some pages in history & memory

### ISSUE THREAD

**Issue by panthernet** [firstfloorsoftware/mui#46]
Hi, i don't want to track some critical pages in myapp so they don't get into history or be cached in memory. Is it somehow possible right now? I've searched the discussions and found some hacky way to clear history, but i wonder if pages are still cached in MUI somewhere?

Can you please point me to the code that is responsible for this process so i can have a look into it? Don't have much time to study the code, thanks!

**Comment by TransientResponse** [comment]
I encountered a similar problem myself. I couldn't find where the "built-in" page history was kept, so I ended up using the instructions [here](http://www.saramgsilva.com/index.php/2014/modern-ui-for-wpf-application-by-example-navigationservice-mvvm/) to implement my own navigation service. You have to override the navigation events on all your pages to hook into your navigation service, but you end up with full control over your page history. Note that you need to pull in MVVMLight as well for this to work. 

I can help you get that set up if you need (and if you have time).

**Comment by ikondrasovas** [comment]
Hi @TransientResponse How do you exactly hook navigation events to you navigation service? I implemented the navigation service you mentioned but I don't see how to add this information to my service history?

I also opened an issue about this issue.,,, #150
