### ISSUE TITLE
Storing individual user settings

### ISSUE THREAD

**Issue by williamhodges** [firstfloorsoftware/mui#49]
I really like MUI. It has helped me take my application from something that looked like 3rd grader built to something a 3rd grader has not built. I was wondering if someone could help me figure out or point me in the right direction (preferably somewhere that can show examples lol learning wpf/c# on my own) on how to implement save user settings feature. Like if I click the "dark" theme, how can I have it set to when I open the program again, its under the dark theme vs the light?

**Comment by FuchsiaSoft** [comment]
Hi,

You can achieve this through user/application settings... The current accent is a System.Windows.Media.Color and the current theme is just a Uri.

Are you using Visual Studio?, I'll put together an example for you using Visual Studio if that helps?

**Comment by FuchsiaSoft** [comment]
@wdhodges actually this was super simple so I've just gone ahead and done it.

There's a repo available for you here: [Mui-SaveSettings-Demo](https://github.com/FuchsiaSoft/Mui-SaveSettings-Demo)

The only code I've added to the stock navigation app template is this:
```cs
Settings.Default.ChosenTheme = AppearanceManager.Current.ThemeSource;
Settings.Default.ChosenFontSize = AppearanceManager.Current.FontSize;
Settings.Default.ChosenAccent = AppearanceManager.Current.AccentColor;

Settings.Default.Save();
```

... with ChosenTheme being a Uri, ChosenFontSize being a FontSize enum from Mui and ChosenAccent being a Color.  All stored in user scope settings.

I've tried it out and works fine for me... this is from my local appdata folder after I ran it and changed stuff around:
```xaml
<configuration>
    <userSettings>
        <ModernUINavigationApp1.Properties.Settings>
            <setting name="ChosenAccent" serializeAs="String">
                <value>#FFA20025</value>
            </setting>
            <setting name="ChosenTheme" serializeAs="String">
                <value>/FirstFloor.ModernUI;component/Assets/ModernUI.Dark.xaml</value>
            </setting>
            <setting name="ChosenFontSize" serializeAs="String">
                <value>Small</value>
            </setting>
        </ModernUINavigationApp1.Properties.Settings>
    </userSettings>
</configuration>
```

**Comment by wdhodges** [comment]
Nice!! I'm hooking this up to my project now. Thank you @FuchsiaSoft you should possibly bring this in as a pull request to merge with the full MUI project.

**Comment by wdhodges** [comment]
So I tried it. I got most of it to work..buut there's an issue.

            Settings.Default.ChosenTheme = AppearanceManager.Current.ThemeSource;
            Settings.Default.ChosenFontSize = AppearanceManager.Current.FontSize;
            Settings.Default.ChosenAccent = AppearanceManager.Current.AccentColor;

            Settings.Default.Save();

The "ChosenTheme", "ChosenFontSize", and "ChosenAccent" are not populating. So in VS 15, the `red error line appears under it` stating that it's not working. I wrote the app.config file like you have. This is what mine looks like:

<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
      <section name="ctac_information_system.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
    </sectionGroup>
  </configSections>
  <userSettings>
    <ctac_information_system.Properties.Settings>
      <setting name="ChosenAccent" serializeAs="String">
        <value>#00000000</value>
      </setting>
      <setting name="ChosenTheme" serializeAs="String">
        <value />
      </setting>
      <setting name="ChosenFontSize" serializeAs="String">
        <value>Large</value>
      </setting>
    </ctac_information_system.Properties.Settings>
  </userSettings>
</configuration>

note really sure what I'm doing wrong. Target framework is .NET 4.5

**Comment by FuchsiaSoft** [comment]
Hi,

You will need to add the settings to your project for it to work, the config file isn't written manually.

Right click on your project in solution explorer, then click Properties.  There will be a Settings tab which may ask if you want to create a default settings file.  In there you can add the settings which will then be accessible in your code.

**Comment by wdhodges** [comment]
So in that file I place the <configuration> code? Sorry for all the questions. I'm self teaching xaml and c#

On Aug 3, 2015 4:25 AM, Chris Wilson <notifications@github.com> wrote:

Hi,

You will need to add the settings to your project for it to work, the config file isn't written manually.

Right click on your project in solution explorer, then click Properties. There will be a Settings tab which may ask if you want to create a default settings file. In there you can add the settings which will then be accessible in your code.

**Comment by FuchsiaSoft** [comment]
No problem, everyone learns at the beginning :)

I think your best bet is to have a look at these articles:
[How to: Add or Remove Application Settings](https://msdn.microsoft.com/en-us/library/vstudio/25zf0ze8(v=vs.100).aspx)
[Dot net perls: Settings](http://www.dotnetperls.com/settings)

That should give you a good idea of how to add settings to a project the usual way that people do it.  The configuration file is created for you by Visual Studio when you do this.

The type that you will need to choose for each of the settings (if you want to do it the way I did) is:

ChosenTheme: ```System.Uri```
ChosenAccent: ```System.Windows.Media.Color```
ChosenFontSize: ```FirstFloor.ModernUI.Presentation.FontSize```

I would also say that settings like this (that is, personalisation options) should be stored user scope rather than application.

**Comment by wdhodges** [comment]
I'll try this tonight. Thank you so much for you help in this!

**Comment by wdhodges** [comment]
This is the error that I keep getting when trying to follow it. I have set the settings going through all the steps you have provided. I just can't seem to get it lol :/

![Image of Error]
(http://i.imgur.com/qtJstFE.png)

**Comment by FuchsiaSoft** [comment]
Your settings is a System.String and it needs to be a System.Uri

You can change that in a drop down, in the same place that you added the settings.  If System.Uri isn't available in the quick list, just click Browse and you can select it manually :)

**Comment by wdhodges** [comment]
It worked! Thank you so much

**Comment by wdhodges** [comment]
Well I thought it worked. I tried changing the theme and then reload the application but it didn't save my current user settings. Should I change the setting level to user or to application?

**Comment by wdhodges** [comment]
never mind i'm stupid lol I didn't see the 'loaded' part -__-
