### ISSUE TITLE
I need more detailed steps in getting started without templates

### ISSUE THREAD

**Issue by tobitech** [firstfloorsoftware/mui#58]
I created a new WPF application but I am having problem adding the ModernUI resources to my app. I couldn't add the resource dictionaries and the projects. can someone give me a detailed step of how to do this easily to add all the Modern UI resources and modifying my app files to use the resources

**Comment by kozw** [comment]
Have you checked the wiki? [Getting started without templates](/firstfloorsoftware/mui/wiki/Getting-started-without-templates)

**Comment by tobitech** [comment]
Okay, thanks for the reference
