### ISSUE TITLE
BBCodeBlock Linebreak

### ISSUE THREAD

**Issue by luni64** [firstfloorsoftware/mui#61]
I can't find a tag to insert a linebreak in a BBCodeBlock. Is there another possibility to break a line?

Thanks a lot

**Comment by kozw** [comment]
A newline character set (\r\n) works, you can add one in the BBCode attribute like so; &#13;&#10;

**Comment by luni64** [comment]
Thanks for the pointer! 
In case someone else needs it: Further googling showed that entering `&#x0d;&#x0a;` in XAML is required to get the \r\n charset.
