### ISSUE TITLE
Cant change image (Smiley)

### ISSUE THREAD

**Issue by locomain** [firstfloorsoftware/mui#66]
I cant seem to find a way to change the smiley image.
is there something i missed?

**Comment by heraclesaraujo** [comment]
just set LogoData="your path" on the ModernWindow

**Comment by macgile** [comment]
to complete the answer,

in MainWindows.xaml :
LogoData="{Binding Source={StaticResource MyLogo}}"

in your ResourceDictionary:
    <Geometry x:Key="MyLogo">
        M 40.9837,............................ Z
    </Geometry>

**Comment by charlesmilette** [comment]
@macgile or directly do this:  

    LogoData="M 40.9837,............................ Z"

like I've done here: https://github.com/charlesmilette/MUI.Themes.Symlinker/blob/master/MUI.Themes.Symlinker/MainWindow.xaml

**Comment by charlesmilette** [comment]
anyone can close this? I can't do it, but it is fixed...

**Comment by macgile** [comment]
@charlesmilette obviously :) (when logoData is not too complicated)

**Comment by locomain** [comment]
actually i mean using a bitmapimage or such.

**Comment by locomain** [comment]
i noticed the part in the documentation that it supports geometry only. i am sorry
