### ISSUE TITLE
Add "Visibility" and "Name" property and "Initialized" method to LinkGroup and Link

### ISSUE THREAD

**Issue by charlesmilette** [firstfloorsoftware/mui#69]
It will help the program to show sections only when certains conditions are respected (example: running as admin)

Kinda like that:
```xaml
        /* ... */
        <mui:LinkGroup DisplayName="file">
            <mui:LinkGroup.Links>
                <mui:Link DisplayName="Symbolic Link" Name="SymLink" Initialized="UserControl_Initialized" Source="/Pages/FileSymbolic.xaml" />
                <mui:Link DisplayName="Hard Link" Source="/Pages/FileHard.xaml" />
            </mui:LinkGroup.Links>
        </mui:LinkGroup>
        /* ... */
```
and the function will be like that:
```c#
        private void UserControl_Initialized(object sender, EventArgs e)
        {
            if (!VistaSecurity.IsAdmin())
            {
                SymLink.Visibility = System.Windows.Visibility.Collapsed;
            }
        }
```
It'll fix #67 also...

**Comment by charlesmilette** [comment]
Any news about that?

**Comment by kozw** [comment]
I'm not sure this is an improvement. A LinkGroup and/or Link is visible when added to a collection. It's hidden when removed. My approach would be to fill the groups and links in a ViewModel, and use bindings to keep the view in sync. Both LinkGroup and Link collections are observable exactly for that purpose.

In my opinion LinkGroup and Link are not part of the View, they do not derive from a dependency object.

**Comment by charlesmilette** [comment]
Okay. I'm gonna live with it.
