### ISSUE TITLE
Menu Link Case

### ISSUE THREAD

**Issue by langatke** [firstfloorsoftware/mui#77]
How can i modify the MenuGroupLinks and LinkGroups to have different Case, i would have preffered if the MenuGroupLink to Upper Case

**Comment by kozw** [comment]
The various controls (such as ModernTab) use ToUpperCase/ToLowerCase value converters for changing the casing. Provide a custom control theme to achieve what you need.

**Comment by zenglian** [comment]
Tab links are upper case by default now. Can you please keep the original case by default?  
To me upper case is not so friendly to user (it's harder to read than normal case for non-native speakers).
