### ISSUE TITLE
Shared.shproj is not opening vs2012

### ISSUE THREAD

**Issue by kjalla** [firstfloorsoftware/mui#79]
Shared.shproj is not opening in vs21012, and still I am getting the below error when I run the app.

![mui error](https://cloud.githubusercontent.com/assets/7868378/11761437/fc1f2076-a0e8-11e5-8e8b-b3cdda827759.jpg)
Any help is appreciated!

Thanks in Advance

**Comment by vinaydwivedi** [comment]
It's not even opening on VS2015 - Windows 7. Can't find any compatible 8.1 project templates for Win7.

**Comment by kozw** [comment]
Shared projects requires Visual Studio 2013 or up. VS2015 should work just fine.
