### ISSUE TITLE
Any new updates coming soon?

### ISSUE THREAD

**Issue by wdhodges** [firstfloorsoftware/mui#84]
Any new updates coming soon to this framework?

**Comment by OrihuelaConde** [comment]
Its a nice framework and well documented. We are using it in various nonprofit projects on our high school.

**Comment by charlesmilette** [comment]
This project was pretty dead before it migrated to GitHub, and got a little activity boost because of it. It seems it is refalling to the "dead" state.

**Comment by wdhodges** [comment]
I've used this framework for my main application and actually love it. I think it's about time for someone to Fork it and make it better with updates. If I was that comfy with WPF I would but it's still a good framework as is.

**Comment by craigmillard** [comment]
I'm also interested in this framework- I'm glad to see you guys among the tumbleweeds!  One of my clients uses this in a LOB application.

**Comment by kozw** [comment]
Hey folks! Mui is not dead, it's hibernating. I really do want to address the reported issues and add a feature or two, but limited free time is preventing me to do so.

This thread actually triggered me to do something about it, expect some updates soon.

**Comment by wdhodges** [comment]
Outstanding! I'm glad I could help. I'll eagerly await the updates!

**Comment by charlesmilette** [comment]
In 30 minutes, you managed to fill half of my news feed. Wow

**Comment by FuchsiaSoft** [comment]
me too!... I'm sooo happy that this library is alive again.  I use it all the time and it's my "go to" for nicely styled WPF apps

Thanks for your work @kozw :thumbsup:

**Comment by OrihuelaConde** [comment]
@kozw, thank you!

**Comment by wdhodges** [comment]
Love the framework!! Does these update the Nuget packages too? :)

**Comment by kozw** [comment]
Thanks! Yes, everything is updated in the latest release (binaries in GitHub release, templates in visual studio gallery, and the nuget package)
