### ISSUE TITLE
MefContentLoader not called in MEF construction

### ISSUE THREAD

**Issue by bhutten14** [firstfloorsoftware/mui#86]
I've followed the instructions in the Wiki for the MEF construction. My views code-behind look all like this:
```
    [Content("/View/EmployeeListView.xaml")]
    public partial class EmployeeListView : IContent
    {
        public EmployeeListView()
        {
            InitializeComponent();
        }

        [Import]
        public EmployeeListViewModel EmployeeListViewModel
        {
            get { return (EmployeeListViewModel)DataContext; }
            set { DataContext = value; }
        }

```
When debugging I can see the view is constructed, and also the view model is constructed by the MEF catalog. But the viewmodel is not set on the view, debugger does not break in setter of property EmployeeListViewModel. Also the MefContentLoader is not called.
Can anybody explain why this is not happening?
Workaround for now is that, in the constructor of the view, I provide access to the container (via MainWindow) to pull out the view model myself and set the DataContext
`DataContext = Container.GetExportedValue<EmployeeListViewModel>()`
which is not so nice :-/

**Comment by bhutten14** [comment]
I discovered some more details about the problem. From all the links I have on the main window, only the 'settings' link (which is a TitleLinks Link) triggers the LoadContent method of MefContentLoader.
Here are all the links on the main window:
```
<mui:ModernWindow.TitleLinks>
        <mui:Link DisplayName="Settings" Source="/View/SettingsView.xaml" />
    </mui:ModernWindow.TitleLinks>

    <mui:ModernWindow.MenuLinkGroups>
        <mui:LinkGroup DisplayName="Werknemers">
            <mui:LinkGroup.Links>
                <mui:Link DisplayName="Alle" Source="/View/EmployeeListView.xaml" />
            </mui:LinkGroup.Links>
        </mui:LinkGroup>
        <mui:LinkGroup DisplayName="Functies">
            <mui:LinkGroup.Links>
                <mui:Link DisplayName="Alle" Source="/View/EmployeeListView.xaml" />
            </mui:LinkGroup.Links>
        </mui:LinkGroup>
        <mui:LinkGroup DisplayName="Trainingen">
            <mui:LinkGroup.Links>
                <mui:Link DisplayName="Alle" Source="/View/EmployeeListView.xaml" />
            </mui:LinkGroup.Links>
        </mui:LinkGroup>
    </mui:ModernWindow.MenuLinkGroups>
```
Why is only that link calling the LoadContent method??

**Comment by kozw** [comment]
As far as I can tell, your code snippets looks fine. Things to double check;

* I'm assuming EmployeeListView does derive from UserControl?
* Any MEF conflicts resolve warnings in the output window?
* Is the MefContentLoader correctly implemented and defined in App.xaml?
* Check the value of the MefContentLoader.Contents property, does it contain all the exported content?

**Comment by bhutten14** [comment]
EmployeeListView  derives from UserControl.
No MEF conflicts resolve warnings in the output window.
The Contents property has three items (Settings, SettingsAppearance and EmployeeListView)
My App.xaml look like the following:
```
<Application x:Class="TrainingManagementTool.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:view="clr-namespace:TrainingManagementTool.View"
             xmlns:mui="http://firstfloorsoftware.com/ModernUI">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/FirstFloor.ModernUI;component/Assets/ModernUI.xaml" />
                <ResourceDictionary Source="/FirstFloor.ModernUI;component/Assets/ModernUI.Light.xaml" />
                <ResourceDictionary>
                    <Style TargetType="mui:ModernFrame">
                        <Setter Property="ContentLoader" Value="{DynamicResource MefContentLoader}" />
                    </Style>
                    <Style TargetType="mui:ModernTab">
                        <Setter Property="ContentLoader" Value="{DynamicResource MefContentLoader}" />
                    </Style>
                    <Style TargetType="view:MainWindow">
                        <Setter Property="ContentLoader" Value="{DynamicResource MefContentLoader}" />
                    </Style>
                </ResourceDictionary>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```
And still I notice that the break point in LoadContent() of MefContentLoader is not hit when clicking the EmployeeListView link, but it does when clicking the Settings link.

**Comment by kozw** [comment]
How is the MefContentLoader instantiated? Is the Contents property properly imported?

**Comment by bhutten14** [comment]
My Bootstrapper class looks like this:
```
    public class Bootstrapper : MefBootstrapper
    {
        protected override DependencyObject CreateShell()
        {
            return Container.GetExportedValue<MainWindow>();
        }

        protected override void InitializeShell()
        {
            base.InitializeShell();

            Container.ComposeParts(this);

            //The MefContentLoader instance is retrieved from the container and added to the global application 
            //resource dictionary. Once the loader is added, the DynamicResource reference used in the default styles can be resolved.
            var contentLoader = Container.GetExportedValue<MefContentLoader>();
            Application.Current.Resources.Add("MefContentLoader", contentLoader);

            // Add the imported resource dictionaries
            // to the application resources
            var views = Container.GetExportedValues<UserControl>();
            foreach (var r in views)
            {
                Application.Current.Resources.MergedDictionaries.Add(r.Resources);
            }

            ((MainWindow) Shell).MainWindowViewModel.Container = Container;
            Application.Current.MainWindow = (Window)Shell;
            Application.Current.MainWindow.Show();
        }

        protected override void ConfigureAggregateCatalog()
        {
            base.ConfigureAggregateCatalog();

            // Add this assembly to export views and viewmodels
            AggregateCatalog.Catalogs.Add(new AssemblyCatalog(typeof(Bootstrapper).Assembly));
        }
    }
```

**Comment by kozw** [comment]
Looks good. Not sure why you would add all user controls to the resource dictionary, but that should not conflict. Care to share the entire codebase?

**Comment by bhutten14** [comment]
Ok, here's a stripped version of the app. Notice when clicking on the menu's the content loader is NOT called, when clicking on settings (Instellingen) link it works as expected and calls the content loader.

[SourceCode.zip](https://github.com/firstfloorsoftware/mui/files/129182/SourceCode.zip)

**Comment by kozw** [comment]
Found two issues;
First, you define a default style for mui:ModernWindow in App.xaml to set the ContentLoader. However, this needs to be the actual main window type TrainingManagementTool.View.MainWindow. So change the style to this (and define the xmlns:local="clr-namespace:TrainingManagementTool.View" );
```
<Style TargetType="local:MainWindow">
  <Setter Property="ContentLoader" Value="{DynamicResource MefContentLoader}" />
</Style>
```

Second, do not define the default style overrides in a merged dictionary. Add them to the main Application.Resources like so;
```
<Application.Resources>
  <ResourceDictionary>
    <ResourceDictionary.MergedDictionaries>
      <ResourceDictionary Source="/FirstFloor.ModernUI;component/Assets/ModernUI.xaml" />
      <ResourceDictionary Source="/FirstFloor.ModernUI;component/Assets/ModernUI.Light.xaml" />
    </ResourceDictionary.MergedDictionaries>

    <!-- style overrides here -->
    <Style TargetType="mui:ModernFrame">
      <Setter Property="ContentLoader" Value="{DynamicResource MefContentLoader}" />
    </Style>
    <!-- etc -->
  </ResourceDictionary>
</Application.Resources>
```
Hope this helps

**Comment by bhutten14** [comment]
Great, this works! Applying the ContentLoader in de app.xaml in the correct way solved the problem. Thanks!

(Prachtig framework, mijn apps zien er gelijk gelikt uit)

**Comment by kozw** [comment]
top!
