### ISSUE TITLE
MEF: ContentLoader not called for source reference in ModernFrame

### ISSUE THREAD

**Issue by bhutten14** [firstfloorsoftware/mui#87]
Another MEF problem:
On the MainWindow all source references are nicely resolved via the MefContentLoader, so the LoadContent(Uri uri) method is called.
But for the ModernFrame on a page the source reference is not loaded via the MefContentLoader.
I use:
`<mui:ModernFrame Grid.Column="2" Source="/View/SummaryView.xaml" Margin="32,0,0,0" />`
But the SummaryView.xaml is not loaded via the MefContentLoader.

See attached solution, when debugging the solution: set breakpoint in MefContentLoader.LoadContent() method. When starting the application the debugger breaks for uri WelcomView.xaml, then when the MainWindow is visible click on the link 'Alle', the the debugger breaks for uri EmployeeListView.xaml. But the debugger does not break for the SummaryView.xaml, which  is expected.
Why is the MefContentLoader not called when loading SummaryView.xaml source in the ModernFrame?

[SourceCode.zip](https://github.com/firstfloorsoftware/mui/files/133339/SourceCode.zip)

**Comment by kozw** [comment]
The Frame.Source is resolved before the default style is applied. If you change the xaml to this, it works;
```
<mui:ModernFrame ContentLoader="{DynamicResource MefContentLoader}" Source="/View/SummaryView.xaml" />
```

If you move the ContentLoader attribute after the Source, it doesn't work;
```
<mui:ModernFrame Source="/View/SummaryView.xaml" ContentLoader="{DynamicResource MefContentLoader}" />
```

**Comment by bhutten14** [comment]
Thanks for this fast answer.

Ok, this works. But didn’t we applied the default style in the app.xaml already? Is it possible to change the framework so the default style is resolved before the Frame.Source?

 

 

Van: Koen Zwikstra [mailto:notifications@github.com] 
Verzonden: dinsdag 16 februari 2016 23:18
Aan: firstfloorsoftware/mui <mui@noreply.github.com>
CC: bhutten14 <bhutten@hotmail.com>
Onderwerp: Re: [mui] MEF: ContentLoader not called for source reference in ModernFrame (#87)

 

The Frame.Source is resolved before the default style is applied. If you change the xaml to this, it works;

<mui:ModernFrame ContentLoader="{DynamicResource MefContentLoader}" Source="/View/SummaryView.xaml" />

If you move the ContentLoader attribute after the Source, it doesn't work;

<mui:ModernFrame Source="/View/SummaryView.xaml" ContentLoader="{DynamicResource MefContentLoader}" />

**Comment by kozw** [comment]
Yes, but apparently the local properties are applied before the default style when the control is instantiated. This behavior is inherent to how the XAML parser is implemented in WPF. I'm not sure there is a way to solve this other than supplying the ContentLoader

**Comment by bhutten14** [comment]
Ok, thanks for your help. I'll just have to add the ContentLoader to the ModernFrame tag.
Maybe you can update the MEF page where you explain how to incorporate MEF in MUI with this finding.

**Comment by kozw** [comment]
It fails in this case because the Source is defined in XAML. I usually define the source in a viewmodel, and bind to it in XAML. In that case it works fine, for bindings are resolved after the ContentLoader default style setter has been applied.
