### ISSUE TITLE
How to destroy a history page (UserControl)

### ISSUE THREAD

**Issue by KevinPan** [firstfloorsoftware/mui#89]
For the first time I navigate to a user control, it creates a new instance, and then if I navigate to that control, it will use the previous created instance. In some case, like user logout and login, I need to destory all the history pages, what shoud I do?

**Comment by kozw** [comment]
Assign attached property ModernFrame.KeepAlive = false to your usercontrol XAML like so:
```
<UserControl .. 
    xmlns:mui="http://firstfloorsoftware.com/ModernUI"
    mui:ModernFrame.KeepAlive="false">
  ..
</UserControl>
```

**Comment by KevinPan** [comment]
It works, thanks!
