### ISSUE TITLE
ModernDialog: change text of button

### ISSUE THREAD

**Issue by robertosalemi** [firstfloorsoftware/mui#9]
Hi, 
I'm using ModernDialog on my application. 

I would replace the text of the button of MessageBoxButton with the text in my language, is it possibile? 

For example: 
replace "Yes" with "Si" and anymore. 

Thanks.

**Comment by picrap** [comment]
Hi, I recently had the same problem, and here is how to solve it:
```xaml
    <mui:ModernDialog.Buttons>
        <x:Array Type="Button">
            <Button Content="Si" />
        </x:Array>
    </mui:ModernDialog.Buttons>

```
You just need to handle the command of the button by yourself.

**Comment by robertosalemi** [comment]
Hi,
I must insert it in APP.xaml of my application?

**Comment by picrap** [comment]
No, in each view that requires it.

**Comment by robertosalemi** [comment]
Sorry, but for create my DialogBox, I'm using:
<code>
var rsltDialog = ModernDialog.ShowMessage("Text to show", "Title of DialogBox", MessageBoxButton.YesNo);
</code>

I would change the text of button that is view across MessageBoxButton.YesNo ;)

**Comment by picrap** [comment]
Sorry I misunderstood the problem. If you don't find any other option, you'll probably have to create your own custom dialog box.

**Comment by robertosalemi** [comment]
I hope find a good solution, thanks!

**Comment by kozw** [comment]
There are two options;

1. Either create a [satelite assembly](http://blogs.msdn.com/b/global_developer/archive/2011/07/22/introduction-to-satellite-assemblies.aspx) for MUI, and provide your own translation for MUI resources. A fairly time-consuming task.

2. Don't use ShowMesssage, but create your own ModernDialog instance and assign your translation to the various ModernDialog buttons. Something like this works;

```c#
var dlg = new ModernDialog{
  Title = title,
  Content = new BBCodeBlock { BBCode = text, Margin = new Thickness(0, 0, 0, 8) },
  MinHeight = 0,
  MinWidth = 0,
  MaxHeight = 480,
  MaxWidth = 640,
};
dlg.OkButton.Content = "Okay";
dlg.CancelButton.Content = "Nope";
dlg.Buttons = new Button { dlg.OkButton, dlg.CancelButton };
dlg.ShowDialog();
var result = dlg.messageBoxResult;
```

**Comment by KevinPan** [comment]
@kozw any suggestions to implement a satelite assembly for MUI? I'm trying this way...
